export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { Navbar } from "../_components/navbar";
import Footer from "../_components/footer";
import dynamic from "next/dynamic";

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-[90vh] flex flex-col justify-center">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// export default

// export default Page;
export default dynamic(() => Promise.resolve(RootLayout), { ssr: false });
