import Footer from "../_components/footer";
import { Navbar } from "../_components/navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-[95vh] flex flex-col justify-center items-center">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
